export const STATE_TYPES = {
  EMPTY: 'EMPTY',
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  NO_INTERNET: 'NO_INTERNET',
  SLOW_NETWORK: 'SLOW_NETWORK',
  NO_SEARCH_RESULTS: 'NO_SEARCH_RESULTS',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  FORM_VALIDATION: 'FORM_VALIDATION',
  SUCCESS: 'SUCCESS'
};
